name: Test github action

on:
  workflow_dispatch:

jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: recursive
          token: ${{ secrets.TOKEN }}

      - name: Check for file changes
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            srcs/*
            versions/*

      - name: Print changed files
        run: |
          echo "Check file changes"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          echo ${{ steps.changed-files.outputs.all_changed_files }};
