name: Test dependency and maintenance of changed files

on:
  workflow_dispatch:
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "test maintenance of changed file" >> test.tmp
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step2
        run: |
          cat test.tmp
    
